#!/usr/bin/env bash
#Fizzbuzz
for i in {1..100}
do
	{ (( i % 5 == 0 )) && ((i % 3 == 0 )) && echo "FizzBuzz"; } ||
	{ (( i % 5 == 0 )) && echo "Buzz"; } ||
	{ (( i % 3 == 0 )) && echo "Fizz"; } ||
		echo $i
done
