#!/usr/bin/env bash
#If While Elif loop

TIMES=0

while [ "$TIMES" -lt 10 ]
do
	TIMES=$((TIMES+1))
	if [ "$TIMES" -eq 4 ]; then
		echo "bad luck"
	elif [ "$TIMES" -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
done
