#!/usr/bin/env bash
#While Case Loop

TIMES=0

while [ "$TIMES" -lt 20 ]
do
	TIMES=$((TIMES+1))
	echo $TIMES
	case $TIMES in 
	4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
	esac
done
