#!/usr/bin/env bash
#Clock with while loop

HOURS=0
MINUTES=0

echo "Hour: $HOURS"

while [ $MINUTES -lt 590 ]
do
	MINUTES=$((MINUTES+1))
	echo $MINUTES

	case $MINUTES in
	59) 
	HOURS=$((HOURS+1))
	MINUTES=0
	echo "Hour: $HOURS";;
	esac
	case $HOURS in
	12)
	exit;;
	esac
done	
