#!/usr/bin/env bash
#Clock with while loop

HOURS=0
while [ "$HOURS" -lt 13 ]
do
	echo "Hour: $HOURS"
	MINUTE=1
	while [ "$MINUTE" -lt 60 ]
	do
		echo $MINUTE
		MINUTE=$((MINUTE+1))
	done
	HOURS=$((HOURS+1))
done	
