#!/usr/bin/env bash
#Check file

FILENAME="school"

if [ -e "$FILENAME" ]; then
	echo "school file exists"
	if [ ! -s $FILENAME ]; then
		echo "school file is empty"
	elif [ -s $FILENAME ]; then
		echo "school file is not empty"
	fi

	if [ -f $FILENAME ]; then
		echo "school is a regular file"
	else
		exit
	fi
else
	echo "school file does not exist"
fi
