#!/usr/bin/env bash
#Process and PID file

touch /var/run/myscript.pid
myscriptpid=$(pidof /var/run/myscript.pid)
echo "$myscriptpid" > /var/run/myscript.pid


trap '( echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit )' SIGTERM
trap '( echo "Y U no love me?!" )' SIGINT
trap '( sudo rm /var/run/myscript.pid; exit )' SIGQUIT
while :
do
	echo "To infinity and beyond"
	sleep 2
done
