#!/usr/bin/env bash
#Process and PID file

touch /var/run/myscript.pid
myscriptpid=$(pidof /var/run/myscript.pid)
echo "$myscriptid" > /var/run/myscript.pid


trap '( echo "I hate the kill command" )' SIGTERM
trap '( echo "Y U no love me?!" )' SIGINT
trap '( rm /var/run/myscript.pid && exit )' SIGQUIT || SIGTERM
while :
do
	echo "To infinity and beyond"

done
