#!/usr/bin/env bash
#Process and PID file

touch /var/run/myscript.pid
myscriptpid=$(pidof /var/run/myscript.pid)
echo "$myscriptpid" > /var/run/myscript.pid
scriptPID=$$

while :
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; kill $scriptPID ' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'sudo rm /var/run/myscript.pid; kill $scriptPID' SIGQUIT
done
