#!/usr/bin/env bash
#Manage my process

scriptPID=$(pidof ./manage_my_process)
FILE=/var/run/my_process.pid

start() {

	sudo touch "$FILE"
	./manage_my_process &
	echo "$scriptPID" > "$FILE"
	echo "manage_my_process started"
}

stop() {

	sudo kill -15 "$scriptPID" && rm -f "$FILE"
	echo "manage_my_process stopped"
}

restart() {

	sudo kill -15 "$scriptPID" && rm -f "$FILE"
	./manage_my_process &
	sudo touch "$FILE"
	echo "$scriptPID" > $FILE
	echo "manage_my_process restarted"
}

case $1 in 
	start) start;;
	stop) stop;;
	restart) restart;;
	*) echo "Usage: manage_my_process {start|stop|restart}"
esac
