#!/usr/bin/env bash
#Manage my process

FILE=/var/run/my_process.pid
FILEPID=$( pgrep -fa | cut -d ' '-f1 ) 
start() {

	sudo touch "$FILE"
	./manage_my_process &
	echo "$FILEPID" > "$FILE"
}

stop() {

	sudo kill -9 "$( cat $FILE )" 
	rm -f "$FILE"
}

case $1 in 
	start) start
	echo "manage_my_process started"
	;;
	stop) stop
	echo "manage_my_process stopped"	
	;;
	restart) restart
	stop
	start
	echo "manage_my_process restarted"	
	;;
	*) echo "Usage: manage_my_process {start|stop|restart}"
esac
